image: rust:1.56.1

pipelines:
  default:
    - step:
        caches:
          - cargo
          - rust-target
        script:
          - cargo test
          - rustup toolchain install nightly
          - RUST_BACKTRACE=1 RUSTFLAGS='-C target-feature=+ssse3,+sse4.1' cargo +nightly test --all-features
          # make sure benchmarks compile
          - cargo +nightly bench --no-run
          - RUSTFLAGS='-C target-feature=+ssse3,+sse4.1' cargo +nightly bench --all-features --no-run

definitions:
  caches:
    cargo: /usr/local/cargo # CARGO_HOME
    rust-target: $BITBUCKET_CLONE_DIR/target
