[build]
rustflags = ["-C", "target-cpu=native"]

[target.'cfg(all(target_arch = "aarch64", target_feature = "neon"))']
rustflags = ["-C", "target-feature=+neon"]

[target.'cfg(all(any(target_arch = "x86_64", target_arch = "x86"), target_feature = "ssse3", target_feature = "sse4.1"))']
rustflags = ["-C", "target-feature=+ssse3,+sse4.1"]
