name: test

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches:
      - main

jobs:
  test-simd:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    # test rust on aarch64 and x86_64
    strategy:
      matrix:
        arch: [ aarch64, x86_64 ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          targets: ${{ matrix.arch }}-unknown-linux-gnu

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Install cross
        run: cargo install cross

      - name: Set crate features by arch
        run: |
          if [ "${{ matrix.arch }}" = "aarch64" ]; then
            echo "CARGO_FEATURES=aarch64_neon" >> $GITHUB_ENV
            echo "TARGET=aarch64-unknown-linux-gnu" >> $GITHUB_ENV
          fi
          if [ "${{ matrix.arch }}" = "x86_64" ]; then
            echo "CARGO_FEATURES=x86_ssse3,x86_sse41" >> $GITHUB_ENV
            echo "TARGET=x86_64-unknown-linux-gnu" >> $GITHUB_ENV
          fi

      - name: Build test suite
        run: cross test --no-run --features=${{ env.CARGO_FEATURES }} --target=${{ env.TARGET }}

      - name: Run tests
        run: RUST_BACKTRACE=1 cross test --features=${{ env.CARGO_FEATURES }} --target=${{ env.TARGET }}

      # make sure benchmarks compile
      - name: Build benchmarks
        run: cross bench --no-run --features=${{ env.CARGO_FEATURES }} --target=${{ env.TARGET }}

      - name: Run benchmarks
        run: cross bench --features=${{ env.CARGO_FEATURES }} --target=${{ env.TARGET }}

  test-scalar:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Build test suite
        run: cargo test --no-run --all-features

      - name: Run tests
        run: RUST_BACKTRACE=1 cross test --all-features

      # make sure benchmarks compile
      - name: Build benchmarks
        run: cross bench --no-run --all-features

      - name: Run benchmarks
        run: cross bench --all-features


